apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  interval: 5m
  chart:
    spec:
      version: "1.8.2"
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    image:
      registry: registry.opensource.zalan.do
      repository: acid/postgres-operator
      tag: v1.8.2-43-g3e148ea5
      pullPolicy: "IfNotPresent"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator-ui
spec:
  interval: 5m
  chart:
    spec:
      version: "1.8.2"
      chart: postgres-operator-ui
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-ui
      interval: 60m
  values:
    image:
      registry: registry.opensource.zalan.do
      repository: acid/postgres-operator-ui
      tag: v1.8.2-43-g3e148ea5
      pullPolicy: "IfNotPresent"
