apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres-operator
spec:
  interval: 2h
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres-operator-ui
spec:
  interval: 2h
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
