apiVersion: v1
kind: Secret
metadata:
    name: ddns-secrets
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Mjhqa6LInV4ZbKxbrT+b/eyGM8R8W6KrOd68+xQDQ5AAvkojBZGZ9A==,iv:oJHbBTYwYkj+PSvqzTVZHWwuuAtWG9ZC3wSvx6mivUs=,tag:S7p44+hGeH79GP4ySqMiLg==,type:str]
    zone: ENC[AES256_GCM,data:DxGAo1sI1rID,iv:HzYwGygkvAO/vtj7WhJI8FJB3545zApdWQ9Cp+U85L0=,tag:KTH56l/bWJH0Acp7JbZNwQ==,type:str]
    dns_record: ENC[AES256_GCM,data:k/HC4XnIWnFcLlc=,iv:lm2k/Lx0aqCmP3+uMYYE/4yNwswN89WSYT9wPurGim0=,tag:Tel0E5K6rfBsUfrS3ZqxSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jxwy9x6323rv22e9wu75phd7x2aze2rfzasjrn04l3asf0l9zfpsk8vffp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTzhVY0J0VncrVW9YMEtJ
            UHloSXdOY1ZOT0FNOXNIS1VHNnFadUVWSHdJClVkNVRzaGNrSmdNcURSOGVrd05k
            dW01K2VZbmFMR1dMSkVEZ3QzUFYwT0EKLS0tIFl0S1hTYVo4UnFxQ1F1eG1pMldE
            b3pYSGkvTTJjcFh5TE15Wm9HSGMyTmMKIVxE0qvg1ed12qACv7EVmsbtBNKaGMER
            uvUIoonXUxvs4cI0Uen+neQC59d7L/8pTHP7BQ87AKpm+HccTRKXlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-12T15:22:10Z"
    mac: ENC[AES256_GCM,data:YWce436vdgOdFot06WD72poqrKJqq0r1t/lXyZSDltTTjk/Vbz/3GJvnb/b+xe+SD4YNizWFqw920qeENkuOyXnE4F/xd2Nhi++3/Gpa8EK7/1Nz6K1daOWXD7y2NWIJJilGKttBDnxrUhCFMLu0Nh/46d0+vztUz2yf0P98QJA=,iv:JCrL0wPvqIJoLjgVSkq0M2kw+vMQE5lR3hNuHyIPWm0=,tag:OFERlwSg3dfapcD54LYhYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
