apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/version: v0.107.19
    app.kubernetes.io/instance: adguard-home
  name: adguard-home
  namespace: adguardhome
stringData:
  AdGuardHome.yaml: |-
    auth_attempts: 5
    beta_bind_port: 0
    bind_host: 0.0.0.0
    bind_port: 80
    block_auth_min: 15
    clients:
      persistent: []
      runtime_sources:
        arp: true
        dhcp: true
        hosts: true
        rdns: true
        whois: true
    debug_pprof: false
    dhcp:
      dhcpv4:
        gateway_ip: ""
        icmp_timeout_msec: 1000
        lease_duration: 86400
        options: []
        range_end: ""
        range_start: ""
        subnet_mask: ""
      dhcpv6:
        lease_duration: 86400
        ra_allow_slaac: false
        ra_slaac_only: false
        range_start: ""
      enabled: false
      interface_name: ""
      local_domain_name: lan
    dns:
      aaaa_disabled: false
      all_servers: false
      allowed_clients: []
      anonymize_client_ip: false
      bind_hosts:
      - 0.0.0.0
      blocked_hosts:
      - version.bind
      - id.server
      - hostname.bind
      blocked_response_ttl: 10
      blocked_services: []
      blocking_ipv4: ""
      blocking_ipv6: ""
      blocking_mode: default
      bogus_nxdomain: []
      bootstrap_dns:
      - 1.1.1.1
      - 8.8.8.8
      cache_optimistic: true
      cache_size: 4194304
      cache_time: 30
      cache_ttl_max: 0
      cache_ttl_min: 0
      disallowed_clients: []
      edns_client_subnet: false
      enable_dnssec: false
      fastest_addr: false
      fastest_timeout: 1s
      filtering_enabled: true
      filters_update_interval: 24
      handle_ddr: true
      ipset: []
      ipset_file: ""
      local_ptr_upstreams: []
      max_goroutines: 300
      parental_block_host: family-block.dns.adguard.com
      parental_cache_size: 1048576
      parental_enabled: false
      port: 53
      private_networks: []
      protection_enabled: true
      querylog_enabled: true
      querylog_file_enabled: true
      querylog_interval: 2160h
      querylog_size_memory: 1000
      ratelimit: 0
      ratelimit_whitelist: []
      refuse_any: true
      rewrites: []
      safebrowsing_block_host: standard-block.dns.adguard.com
      safebrowsing_cache_size: 1048576
      safebrowsing_enabled: false
      safesearch_cache_size: 1048576
      safesearch_enabled: false
      serve_http3: false
      statistics_interval: 90
      trusted_proxies:
      - 127.0.0.0/8
      - ::1/128
      upstream_dns:
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query
      upstream_dns_file: ""
      upstream_timeout: 10s
      use_http3_upstreams: false
      use_private_ptr_resolvers: true
    filters:
    - enabled: true
      id: 1
      name: AdGuard DNS filter
      url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    - enabled: true
      id: 2
      name: AdAway Default Blocklist
      url: https://adaway.org/hosts.txt
    - enabled: true
      id: 4
      name: MalwareDomainList.com Hosts List
      url: https://www.malwaredomainlist.com/hostslist/hosts.txt
    - enabled: true
      id: 1619963824
      name: Dan Pollock's List
      url: https://someonewhocares.org/hosts/zero/hosts
    - enabled: true
      id: 1619963825
      name: Game Console Adblock List
      url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
    - enabled: true
      id: 1619963826
      name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
      url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
    - enabled: true
      id: 1619963827
      name: Peter Lowe's List
      url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
    - enabled: true
      id: 1619963828
      name: WindowsSpyBlocker - Hosts spy rules
      url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    - enabled: true
      id: 1619963829
      name: NoCoin Filter List
      url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
    - enabled: true
      id: 1619963830
      name: Scam Blocklist by DurableNapkin
      url: https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
    - enabled: true
      id: 1619963831
      name: The Big List of Hacked Malware Web Sites
      url: https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts
    - enabled: true
      id: 1619963832
      name: Spam404
      url: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
    - enabled: true
      id: 1619963833
      name: Online Malicious URL Blocklist
      url: https://curben.gitlab.io/malware-filter/urlhaus-filter-agh-online.txt
    - enabled: true
      id: 1619963834
      name: 'CHN: anti-AD'
      url: https://anti-ad.net/easylist.txt
    - enabled: true
      id: 1619963835
      name: 'IRN: Unwanted Iranian domains'
      url: https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/unwanted-iranian.txt
    - enabled: true
      id: 1619963836
      name: 'IDN: ABPindo'
      url: https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt
    - enabled: true
      id: 1619963837
      name: 'ITA: Filtri-DNS'
      url: https://filtri-dns.ga/filtri.txt
    - enabled: true
      id: 1619963838
      name: 'KOR: YousList'
      url: https://raw.githubusercontent.com/yous/YousList/master/hosts.txt
    - enabled: true
      id: 1619963839
      name: 'MKD: Macedonian Pi-hole Blocklist'
      url: https://raw.githubusercontent.com/cchevy/macedonian-pi-hole-blocklist/master/hosts.txt
    - enabled: true
      id: 1619963840
      name: BarbBlock
      url: https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt
    - enabled: true
      id: 1647566423
      name: Dandelion Sprout's Anti-Malware List
      url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt
    - enabled: true
      id: 1647566424
      name: OISD Blocklist Basic
      url: https://abp.oisd.nl/basic/
    - enabled: true
      id: 1659912655
      name: 'VNM: ABPVN List'
      url: https://abpvn.com/android/abpvn.txt
    - enabled: true
      id: 1659912656
      name: 'POL: Polish filters for Pi hole'
      url: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt
    - enabled: true
      id: 1659912657
      name: 'SWE: Frellwit''s Swedish Hosts File'
      url: https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt
    - enabled: true
      id: 1659912658
      name: Online Malicious URL Blocklist
      url: https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh-online.txt
    - enabled: true
      id: 1659912659
      name: 'NOR: Dandelion Sprouts nordiske filtre'
      url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersAdGuardHome.txt
    - enabled: true
      id: 1659912660
      name: 'NLD: Easylist'
      url: https://easylist-downloads.adblockplus.org/easylistdutch.txt
    - enabled: true
      id: 1668508346
      name: 1Hosts (Lite)
      url: https://badmojr.gitlab.io/1hosts/Lite/adblock.txt
    - enabled: true
      id: 1668508347
      name: The NoTracking blocklist
      url: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/adblock/adblock.txt
    - enabled: true
      id: 1668508348
      name: Steven Black's List
      url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    - enabled: true
      id: 1668508349
      name: Energized Spark
      url: https://block.energized.pro/spark/formats/filter
    - enabled: true
      id: 1668508350
      name: OISD Blocklist Full
      url: https://abp.oisd.nl/
    - enabled: true
      id: 1668508351
      name: Phishing URL Blocklist (PhishTank and OpenPhish)
      url: https://malware-filter.gitlab.io/malware-filter/phishing-filter-agh.txt
    - enabled: true
      id: 1668508352
      name: Stalkerware Indicators List
      url: https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
    - enabled: true
      id: 1668508353
      name: Malicious URL Blocklist (URLHaus)
      url: https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt
    http_proxy: ""
    language: ""
    log_compress: false
    log_file: ""
    log_localtime: false
    log_max_age: 3
    log_max_backups: 0
    log_max_size: 100
    os:
      group: ""
      rlimit_nofile: 0
      user: ""
    schema_version: 14
    tls:
      allow_unencrypted_doh: false
      certificate_chain: ""
      certificate_path: ""
      dnscrypt_config_file: ""
      enabled: false
      force_https: false
      port_dns_over_quic: 784
      port_dns_over_tls: 853
      port_dnscrypt: 0
      port_https: 443
      private_key: ""
      private_key_path: ""
      server_name: ""
      strict_sni_check: false
    user_rules: []
    users:
    - name: krosf
      password: $2y$10$Ny47lhDW20P/FaY3FB04Y.SEdG4XbnI780AmWYLJ7rjf1khSSrsBK
    verbose: false
    web_session_ttl: 720
    whitelist_filters:
    - enabled: true
      id: 1635063866
      name: Z1
      url: https://gist.githubusercontent.com/KROSF/90bc861d838137d41c7aeaec141d8571/raw/adguard.txt
