apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home
  namespace: adguardhome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
